//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBChestTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBChestTracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent Clanmates Cleaner.
        /// </summary>
        public static string AbsentClanmatesCleaner {
            get {
                return ResourceManager.GetString("AbsentClanmatesCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Creator.
        /// </summary>
        public static string ChestBuilder {
            get {
                return ResourceManager.GetString("ChestBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan.
        /// </summary>
        public static string Clan {
            get {
                return ResourceManager.GetString("Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Chest Manager.
        /// </summary>
        public static string ClanChestManager {
            get {
                return ResourceManager.GetString("ClanChestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Clan Insights.
        /// </summary>
        public static string ClanInsightsTooltip {
            get {
                return ResourceManager.GetString("ClanInsightsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Manager.
        /// </summary>
        public static string ClanManager {
            get {
                return ResourceManager.GetString("ClanManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clanmate Manager.
        /// </summary>
        public static string ClanmateManager {
            get {
                return ResourceManager.GetString("ClanmateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clanmate Validation.
        /// </summary>
        public static string ClanmateValidation {
            get {
                return ResourceManager.GetString("ClanmateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Console Window.
        /// </summary>
        public static string ConsoleWindowTooltip {
            get {
                return ResourceManager.GetString("ConsoleWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Chest Data.
        /// </summary>
        public static string ExportChestData {
            get {
                return ResourceManager.GetString("ExportChestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic.
        /// </summary>
        public static string Heroic {
            get {
                return ResourceManager.GetString("Heroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch OCR Studio.
        /// </summary>
        public static string LaunchOCRWizardTooltip {
            get {
                return ResourceManager.GetString("LaunchOCRWizardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Clan Database.
        /// </summary>
        public static string LoadClanDatabase {
            get {
                return ResourceManager.GetString("LoadClanDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string lvl {
            get {
                return ResourceManager.GetString("lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Clan Chest Settings.
        /// </summary>
        public static string ManageClanChestSettingsTooltip {
            get {
                return ResourceManager.GetString("ManageClanChestSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Clanmate(s).
        /// </summary>
        public static string ManageClanmatesTooltip {
            get {
                return ResourceManager.GetString("ManageClanmatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Clan(s).
        /// </summary>
        public static string ManageClansTooltip {
            get {
                return ResourceManager.GetString("ManageClansTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Wizard.
        /// </summary>
        public static string OCRWizard {
            get {
                return ResourceManager.GetString("OCRWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypt.
        /// </summary>
        public static string OnlyCrypt {
            get {
                return ResourceManager.GetString("OnlyCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become An Patreon.
        /// </summary>
        public static string Patreon {
            get {
                return ResourceManager.GetString("Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Opened Databases.
        /// </summary>
        public static string RecentOpenedDatabases {
            get {
                return ResourceManager.GetString("RecentOpenedDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report A Issue.
        /// </summary>
        public static string ReportAnIssue {
            get {
                return ResourceManager.GetString("ReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Clan Chest Data.
        /// </summary>
        public static string RestoreClanChestData {
            get {
                return ResourceManager.GetString("RestoreClanChestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Clan Database.
        /// </summary>
        public static string SaveClanDatabase {
            get {
                return ResourceManager.GetString("SaveClanDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string SaveClanDatabaseAs {
            get {
                return ResourceManager.GetString("SaveClanDatabaseAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Automation.
        /// </summary>
        public static string StartAutomationTooltip {
            get {
                return ResourceManager.GetString("StartAutomationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Automation.
        /// </summary>
        public static string StopAutomationTooltip {
            get {
                return ResourceManager.GetString("StopAutomationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalBattleGuide on Youtube.
        /// </summary>
        public static string TotalBattleGuideYoutube {
            get {
                return ResourceManager.GetString("TotalBattleGuideYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Notification.
        /// </summary>
        public static string UpgradeNotification {
            get {
                return ResourceManager.GetString("UpgradeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Available.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Clan Chest Integrity.
        /// </summary>
        public static string ValidateClanChestIntegrity {
            get {
                return ResourceManager.GetString("ValidateClanChestIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Chest Data Integrity.
        /// </summary>
        public static string VerifyChestDataIntegrity {
            get {
                return ResourceManager.GetString("VerifyChestDataIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Github Project Page.
        /// </summary>
        public static string VisitGithubProjectPage {
            get {
                return ResourceManager.GetString("VisitGithubProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
